### ISSUE TITLE
Implement website as designs

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#1]
**What:** Implement website as designs

**Why:** Design uses our current style guide, by doing this we will have our app to look like the rest of our platform

**How:** Designs are currently hosted in Notion, we will migrate this to Figma when we get the final designs. For now we can implement from Notion. 

**_Ask for the link developers and please don't post it here since is not meant to be public yet_**

- [x]  Setup the project
- [x]  Minimal raw skeleton
- [x]  Hero section
- [x]  Notification banner *"We are winning"*
- [x]  Informative section
- [x]  Massive call-to-action section
- [x]  Rich informative section *(it has "testimonies" and "call-to-action")*
- [x]  FAQs section
- [ ]  Sidebar control *(one page scroll index)* re #10 
- [ ]  One page scroll feature #10 
- [x]  Header integration *(one of our headers)* re #12

**Comment by duranmla** [comment]
After taking a look to the designs the _"Progress Roadmap"_ for this task looks like this:

## Progress Roadmap

### Kick-off

- [ ]  Setup the project
- [ ]  Minimal raw skeleton

### Static Development

- [ ]  Hero section
- [ ]  Notification banner *"We are winning"*
- [ ]  Informative section
- [ ]  Rich informative section *(it has "testimonies" and "call-to-action")*
- [ ]  FAQs section
- [ ]  Massive call-to-action section

### One page scroll

- [ ]  Sidebar control *(one page scroll index)*
- [ ]  One page scroll feature

### Header integration

- [ ]  Header integration *(one of our headers)*

---

Afterwards, we need to add things like the SSO, actions by users and CMS capabilities.

**Comment by orlando** [comment]
@duranmla I moved this to be an Epic and created tickets for specific sections of the page following your To Do list. You can move to in progress the section you are currently working on and move this Epic to the Epics column

**Comment by duranmla** [comment]
For the side bar control and the one page scroll I think we should re-think if we really need it or wanted. Currently the website have a configuration to allow us to add a social share button on the left side. 

![image](https://user-images.githubusercontent.com/1425162/69873175-df20b800-12b7-11ea-963b-0fa9db0e9532.png)

Let's discuss if we still want those one page scroll features and then close or continue with this.

**Comment by duranmla** [comment]
We speak today that we will be doing the side bar control ven when we are not sure we are going to use it. Since we need to fill the design expectations.

**Comment by duranmla** [comment]
At this point we are working towards inclusion of other things, one page scroll and the widget on the left side to support that feature seems not longer needed _(or if so can be tackle in a different issue)_
