### ISSUE TITLE
Page Sharing

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#22]
**What:**
Add support for buttons on the hero section to being able to share the website.

**Acceptance Criteria**
- [x] Share on Twitter
- [x] Share on Facebook
- [x] Share on LinkedIn **Optional**

re #21
