### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#3]
**What:** Integrate Login and Signup with SSO

**Why:** All of our services use SSO at the moment, we want this to be possible in this app too. We will need to integrate permissions also, so users that belong to a specific group will have admin access in this application.

**How:** We have some reference implementation in Node.js that we can use here too, this is in the dispute-tools repo. The flow should be the same.

**Acceptance Criteria:**
- [x] User should be able to trigger a login flow from the website
- [x] User should be able to trigger a signup flow from the website
- [x] User should be able to trigger a logout from the website
- [x] User should be able to see its session through all ours platforms 

re https://github.com/debtcollective/student-debt-campaign/issues/24
re https://github.com/debtcollective/student-debt-campaign/issues/23

_Note: to being able to properly use the SSO implementation we have the service https://github.com/debtcollective/campaign-api needs to be updated to use the session cookie_

**Comment by duranmla** [comment]
I need both of the pull request get merged in order to move forward with this milestone. CC: @orlando please take a look at them.

**Comment by duranmla** [comment]
Those two branches within the campaign service and the campaign website are being worked together in order to being able to display the actions using the current user logged within the community.

Few things missing is related to the fact of using a dynamic campaignId to return the current campaign in the service and also prompt the user to login in `/actions` path _(or create the authorised page)_

**Comment by duranmla** [comment]
In order to close this Sessions issue I just need to update the Header component after the login has happened. In that sense, I can make a PR with both commits updates above and the update for the header _(that still pending)_
