### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#31]
**Acceptance Criteria:**
- [x] User should be able to see actions to spread the word on `/actions` page
- [x] User should be able to complete actions to spread the word on `/actions` page
- [ ] User should be able to access to `/actions` page only when is logged in
- [x] User should be able to see only the actions that belong to him

_Note: we currently only support actions of type LINK, besides, the full development of this feature needs updates within the service develop at https://github.com/debtcollective/campaign-api_

**Comment by duranmla** [comment]
After merge this PR https://github.com/debtcollective/student-debt-campaign/pull/51 I will be able to add a link into the profile dropdown to allow the user to go to the `/actions` page. And while we are not adding authenticated routes if a guest go to that route nothing is going to be render.

In that sense, I think that we could move forward with that approach and close this milestone like that. Then we can iterate if it is worthy

**Comment by orlando** [comment]
@duranmla the `Actions` link should in the main header along with the other links. Having the users to tell there's an `Actions` link inside the dropdown sounds like a lot of troubles for them.

If you visit that with a session, we should redirect to the home with a message saying "You need to join the campaign before viewing this page"
